import { userModel } from "../models/index.js";
import bcrypt from "bcryptjs";

const users = [
  {
    name: "Mita Kovač",
    email: "mita.kovac@example.com",
    password: "Abcd@1234",
    date_of_birth: "1958-09-21",
    phone_number: "017-5643-917",
    address: "2437 Lukovska Merošina Serbia",
    image_url: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    name: "Noélie Blanc",
    email: "noelie.blanc@example.com",
    password: "Abcd@1234",
    date_of_birth: "1975-01-18",
    phone_number: "05-38-78-59-67",
    address: "3022 Route de Genas Aubervilliers France",
    image_url: "https://randomuser.me/api/portraits/women/86.jpg",
  },
  {
    name: "Gökhan Tahincioğlu",
    email: "gokhan.tahincioglu@example.com",
    password: "Abcd@1234",
    date_of_birth: "1986-09-28",
    phone_number: "(956)-926-9546",
    address: "5737 Maçka Cd Artvin Turkey",
    image_url: "https://randomuser.me/api/portraits/men/59.jpg",
  },
  {
    name: "Alyssa Lijten",
    email: "alyssa.lijten@example.com",
    password: "Abcd@1234",
    date_of_birth: "1985-01-20",
    phone_number: "(0900) 091093",
    address: "8491 Kleine Schelluinsekade Oosterhout Netherlands",
    image_url: "https://randomuser.me/api/portraits/women/84.jpg",
  },
  {
    name: "Oliver Kristensen",
    email: "oliver.kristensen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1996-08-29",
    phone_number: "43938507",
    address: "3629 Egernvej Kongsvinger Denmark",
    image_url: "https://randomuser.me/api/portraits/men/93.jpg",
  },
  {
    name: "Hervé Simon",
    email: "herve.simon@example.com",
    password: "Abcd@1234",
    date_of_birth: "1993-05-08",
    phone_number: "076 138 67 80",
    address: "5464 Esplanade du 9 Novembre 1989 Trasadingen Switzerland",
    image_url: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    name: "احسان سالاری",
    email: "hsn.slry@example.com",
    password: "Abcd@1234",
    date_of_birth: "1981-07-23",
    phone_number: "001-21994718",
    address: "4425 شهید عباس افضلی قم Iran",
    image_url: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    name: "مرسانا حیدری",
    email: "mrsn.hydry@example.com",
    password: "Abcd@1234",
    date_of_birth: "1972-12-10",
    phone_number: "005-05698034",
    address: "7252 آیت الله سعیدی زاهدان Iran",
    image_url: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    name: "Florence Davidson",
    email: "florence.davidson@example.com",
    password: "Abcd@1234",
    date_of_birth: "1983-03-29",
    phone_number: "017687 32267",
    address: "2293 Park Avenue Chester United Kingdom",
    image_url: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    name: "Isla Kallio",
    email: "isla.kallio@example.com",
    password: "Abcd@1234",
    date_of_birth: "1964-10-05",
    phone_number: "07-254-497",
    address: "4952 Visiokatu Viitasaari Finland",
    image_url: "https://randomuser.me/api/portraits/women/87.jpg",
  },
  {
    name: "Heike Olivier",
    email: "heike.olivier@example.com",
    password: "Abcd@1234",
    date_of_birth: "1998-07-14",
    phone_number: "075 441 79 43",
    address: "3938 Rue de la Fontaine Rickenbach (Bl) Switzerland",
    image_url: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    name: "Marcus Evans",
    email: "marcus.evans@example.com",
    password: "Abcd@1234",
    date_of_birth: "1970-04-08",
    phone_number: "(254)-193-1844",
    address: "8943 Castle Street Nelson New Zealand",
    image_url: "https://randomuser.me/api/portraits/men/90.jpg",
  },
  {
    name: "Drago Köcher",
    email: "drago.kocher@example.com",
    password: "Abcd@1234",
    date_of_birth: "1996-01-30",
    phone_number: "0635-8193028",
    address: "3792 Ringstraße Wasserburg am Inn Germany",
    image_url: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    name: "Mila Michel",
    email: "mila.michel@example.com",
    password: "Abcd@1234",
    date_of_birth: "1959-06-14",
    phone_number: "02-19-32-08-87",
    address: "8948 Place du 22 Novembre 1943 Metz France",
    image_url: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    name: "Friederike Schreiter",
    email: "friederike.schreiter@example.com",
    password: "Abcd@1234",
    date_of_birth: "1988-07-23",
    phone_number: "0697-4523499",
    address: "7908 Bergstraße Pohlheim Germany",
    image_url: "https://randomuser.me/api/portraits/women/88.jpg",
  },
  {
    name: "Victor White",
    email: "victor.white@example.com",
    password: "Abcd@1234",
    date_of_birth: "1988-12-18",
    phone_number: "U29 Y32-0785",
    address: "3979 Alfred St Aylmer Canada",
    image_url: "https://randomuser.me/api/portraits/men/86.jpg",
  },
  {
    name: "Dianne Wright",
    email: "dianne.wright@example.com",
    password: "Abcd@1234",
    date_of_birth: "1992-07-06",
    phone_number: "08-3935-6793",
    address: "7054 Preston Rd Melbourne Australia",
    image_url: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    name: "Angela Owens",
    email: "angela.owens@example.com",
    password: "Abcd@1234",
    date_of_birth: "1953-11-01",
    phone_number: "031-304-5327",
    address: "8410 The Crescent Passage West Ireland",
    image_url: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    name: "Konsta Hannula",
    email: "konsta.hannula@example.com",
    password: "Abcd@1234",
    date_of_birth: "1967-10-25",
    phone_number: "04-489-669",
    address: "7471 Satakennankatu Vårdö Finland",
    image_url: "https://randomuser.me/api/portraits/men/81.jpg",
  },
  {
    name: "Alice Arnaud",
    email: "alice.arnaud@example.com",
    password: "Abcd@1234",
    date_of_birth: "1999-10-31",
    phone_number: "05-83-10-00-05",
    address: "4733 Rue de L'Abbé-Groult Clermont-Ferrand France",
    image_url: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    name: "Catalina Patiño",
    email: "catalina.patino@example.com",
    password: "Abcd@1234",
    date_of_birth: "1979-06-15",
    phone_number: "(635) 449 8694",
    address: "2532 Callejón Páez Cherán Mexico",
    image_url: "https://randomuser.me/api/portraits/women/56.jpg",
  },
  {
    name: "Ramona Davis",
    email: "ramona.davis@example.com",
    password: "Abcd@1234",
    date_of_birth: "1950-09-07",
    phone_number: "00-5473-6086",
    address: "6888 Depaul Dr Bunbury Australia",
    image_url: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    name: "Alta Gracia Haro",
    email: "altagracia.haro@example.com",
    password: "Abcd@1234",
    date_of_birth: "1954-08-11",
    phone_number: "(613) 266 4390",
    address: "5288 Avenida Sur Guevara Villa Mariano Matamoros Mexico",
    image_url: "https://randomuser.me/api/portraits/women/83.jpg",
  },
  {
    name: "Naomi Anderson",
    email: "naomi.anderson@example.com",
    password: "Abcd@1234",
    date_of_birth: "1952-10-28",
    phone_number: "(145)-551-6057",
    address: "3785 Mokoia Road Napier New Zealand",
    image_url: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    name: "Ruby Colunga",
    email: "ruby.colunga@example.com",
    password: "Abcd@1234",
    date_of_birth: "1992-03-02",
    phone_number: "(658) 060 0776",
    address: "1342 Ampliación Hidalgo Tecoanapa Mexico",
    image_url: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    name: "Efe Erberk",
    email: "efe.erberk@example.com",
    password: "Abcd@1234",
    date_of_birth: "1983-09-19",
    phone_number: "(549)-403-3403",
    address: "1714 Doktorlar Cd Trabzon Turkey",
    image_url: "https://randomuser.me/api/portraits/men/49.jpg",
  },
  {
    name: "Orlando Rivas",
    email: "orlando.rivas@example.com",
    password: "Abcd@1234",
    date_of_birth: "1973-09-05",
    phone_number: "(608) 547 4315",
    address: "7652 Peatonal Sánchez La Escondida Mexico",
    image_url: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    name: "Victor Johansen",
    email: "victor.johansen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1970-03-05",
    phone_number: "67046379",
    address: "2394 Engvangen Kvistgaard Denmark",
    image_url: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    name: "Linda Foster",
    email: "linda.foster@example.com",
    password: "Abcd@1234",
    date_of_birth: "1970-09-14",
    phone_number: "(317) 918-7845",
    address: "8658 Washington Ave North Valley United States",
    image_url: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    name: "Carl Gommers",
    email: "carl.gommers@example.com",
    password: "Abcd@1234",
    date_of_birth: "1956-02-07",
    phone_number: "(068) 1251799",
    address: "4369 Branderspad Burgwerd Netherlands",
    image_url: "https://randomuser.me/api/portraits/men/28.jpg",
  },
  {
    name: "Gavin Collins",
    email: "gavin.collins@example.com",
    password: "Abcd@1234",
    date_of_birth: "1980-03-18",
    phone_number: "05-0108-4887",
    address: "1721 Timber Wolf Trail Geelong Australia",
    image_url: "https://randomuser.me/api/portraits/men/85.jpg",
  },
  {
    name: "Elmer Lee",
    email: "elmer.lee@example.com",
    password: "Abcd@1234",
    date_of_birth: "1972-09-08",
    phone_number: "(350) 606-9533",
    address: "6352 Oak Lawn Ave Addison United States",
    image_url: "https://randomuser.me/api/portraits/men/83.jpg",
  },
  {
    name: "Viivi Laitinen",
    email: "viivi.laitinen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1988-12-02",
    phone_number: "04-313-090",
    address: "1832 Itsenäisyydenkatu Oulu Finland",
    image_url: "https://randomuser.me/api/portraits/women/74.jpg",
  },
  {
    name: "Susanne Andrews",
    email: "susanne.andrews@example.com",
    password: "Abcd@1234",
    date_of_birth: "1947-09-02",
    phone_number: "061-755-7032",
    address: "6374 Park Road Limerick Ireland",
    image_url: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    name: "Joao Arnaud",
    email: "joao.arnaud@example.com",
    password: "Abcd@1234",
    date_of_birth: "1971-01-28",
    phone_number: "078 552 69 61",
    address: "6380 Rue Paul-Duvivier Klingnau Switzerland",
    image_url: "https://randomuser.me/api/portraits/men/27.jpg",
  },
  {
    name: "Mia Gill",
    email: "mia.gill@example.com",
    password: "Abcd@1234",
    date_of_birth: "1993-11-15",
    phone_number: "K62 L47-0041",
    address: "547 Lake of Bays Road Brockton Canada",
    image_url: "https://randomuser.me/api/portraits/women/75.jpg",
  },
  {
    name: "Ülkü Hakyemez",
    email: "ulku.hakyemez@example.com",
    password: "Abcd@1234",
    date_of_birth: "1976-01-17",
    phone_number: "(837)-702-8986",
    address: "6428 Kushimoto Sk Osmaniye Turkey",
    image_url: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    name: "Valdemar Jensen",
    email: "valdemar.jensen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1961-12-23",
    phone_number: "15071552",
    address: "9463 Østerskovvej Horsens Denmark",
    image_url: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    name: "Tamar Uittenbogaard",
    email: "tamar.uittenbogaard@example.com",
    password: "Abcd@1234",
    date_of_birth: "1977-10-05",
    phone_number: "(0244) 930400",
    address: "4327 Cor Keestraat Ulft Netherlands",
    image_url: "https://randomuser.me/api/portraits/men/59.jpg",
  },
  {
    name: "Budislav Shvec",
    email: "budislav.shvec@example.com",
    password: "Abcd@1234",
    date_of_birth: "1972-01-30",
    phone_number: "(066) W39-9475",
    address: "3439 Provulok Vavilova Uzin Ukraine",
    image_url: "https://randomuser.me/api/portraits/men/23.jpg",
  },
  {
    name: "Eckard Palm",
    email: "eckard.palm@example.com",
    password: "Abcd@1234",
    date_of_birth: "1963-10-14",
    phone_number: "0812-1628498",
    address: "7027 Fliederweg Liebenau Germany",
    image_url: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    name: "Sanni Wirta",
    email: "sanni.wirta@example.com",
    password: "Abcd@1234",
    date_of_birth: "1969-06-10",
    phone_number: "04-671-414",
    address: "8410 Nordenskiöldinkatu Joroinen Finland",
    image_url: "https://randomuser.me/api/portraits/women/89.jpg",
  },
  {
    name: "Mons Haaland",
    email: "mons.haaland@example.com",
    password: "Abcd@1234",
    date_of_birth: "1982-10-06",
    phone_number: "53839957",
    address: "665 Nordbergbakken Lofthus Norway",
    image_url: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    name: "Luke Jones",
    email: "luke.jones@example.com",
    password: "Abcd@1234",
    date_of_birth: "1979-06-22",
    phone_number: "(148)-592-5712",
    address: "6314 Hillsborough Road Blenheim New Zealand",
    image_url: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    name: "پارمیس علیزاده",
    email: "prmys.aalyzdh@example.com",
    password: "Abcd@1234",
    date_of_birth: "1970-06-15",
    phone_number: "077-71944357",
    address: "2728 اقبال لاهوری آمل Iran",
    image_url: "https://randomuser.me/api/portraits/women/24.jpg",
  },
  {
    name: "Johan Schmitt",
    email: "johan.schmitt@example.com",
    password: "Abcd@1234",
    date_of_birth: "1953-08-28",
    phone_number: "05-77-18-36-94",
    address: "8769 Boulevard de Balmont Vitry-sur-Seine France",
    image_url: "https://randomuser.me/api/portraits/men/66.jpg",
  },
  {
    name: "Francisca Reyes",
    email: "francisca.reyes@example.com",
    password: "Abcd@1234",
    date_of_birth: "1952-10-21",
    phone_number: "923-841-510",
    address: "8829 Calle de Bravo Murillo Córdoba Spain",
    image_url: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    name: "Frankie Snyder",
    email: "frankie.snyder@example.com",
    password: "Abcd@1234",
    date_of_birth: "1989-04-04",
    phone_number: "017687 34020",
    address: "1618 Grove Road York United Kingdom",
    image_url: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Rodrigo da Cruz",
    email: "rodrigo.dacruz@example.com",
    password: "Abcd@1234",
    date_of_birth: "1981-02-21",
    phone_number: "(43) 0274-7435",
    address: "9484 Rua Piauí  Caucaia Brazil",
    image_url: "https://randomuser.me/api/portraits/men/53.jpg",
  },
  {
    name: "Helmi Niva",
    email: "helmi.niva@example.com",
    password: "Abcd@1234",
    date_of_birth: "1961-09-18",
    phone_number: "08-549-313",
    address: "9299 Suvantokatu Mänttä Finland",
    image_url: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    name: "Aaliyah Jones",
    email: "aaliyah.jones@example.com",
    password: "Abcd@1234",
    date_of_birth: "1947-02-10",
    phone_number: "(135)-618-3617",
    address: "8282 Napier-Hastings Expressway Dunedin New Zealand",
    image_url: "https://randomuser.me/api/portraits/women/52.jpg",
  },
  {
    name: "Mya Gerard",
    email: "mya.gerard@example.com",
    password: "Abcd@1234",
    date_of_birth: "1953-09-26",
    phone_number: "05-13-12-27-89",
    address: "3115 Place de L'Abbé-Franz-Stock Caen France",
    image_url: "https://randomuser.me/api/portraits/women/84.jpg",
  },
  {
    name: "Lisette Spörl",
    email: "lisette.sporl@example.com",
    password: "Abcd@1234",
    date_of_birth: "1977-08-17",
    phone_number: "0659-0701986",
    address: "4142 Dorfstraße Bad Teinach-Zavelstein Germany",
    image_url: "https://randomuser.me/api/portraits/women/29.jpg",
  },
  {
    name: "Martin Hale",
    email: "martin.hale@example.com",
    password: "Abcd@1234",
    date_of_birth: "1992-10-31",
    phone_number: "015242 12805",
    address: "2825 Queensway St Davids United Kingdom",
    image_url: "https://randomuser.me/api/portraits/men/80.jpg",
  },
  {
    name: "Jake Walker",
    email: "jake.walker@example.com",
    password: "Abcd@1234",
    date_of_birth: "1980-02-15",
    phone_number: "(570)-425-6391",
    address: "2171 Prestons Road Auckland New Zealand",
    image_url: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Nikolaj Althaus",
    email: "nikolaj.althaus@example.com",
    password: "Abcd@1234",
    date_of_birth: "1979-10-17",
    phone_number: "0163-6084688",
    address: "7731 Im Winkel Lengerich Germany",
    image_url: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    name: "Giacomo Lopez",
    email: "giacomo.lopez@example.com",
    password: "Abcd@1234",
    date_of_birth: "1965-02-19",
    phone_number: "075 445 86 64",
    address: "4064 Avenue Debourg Rorbas Switzerland",
    image_url: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    name: "Sandra Peixoto",
    email: "sandra.peixoto@example.com",
    password: "Abcd@1234",
    date_of_birth: "1999-10-31",
    phone_number: "(39) 2877-4981",
    address: "9822 Rua Das Flores  Rio Claro Brazil",
    image_url: "https://randomuser.me/api/portraits/women/83.jpg",
  },
  {
    name: "Yosifata Chechel",
    email: "yosifata.chechel@example.com",
    password: "Abcd@1234",
    date_of_birth: "1983-06-29",
    phone_number: "(066) I96-7984",
    address: "121 Danila Galickogo Novograd-Volinskiy Ukraine",
    image_url: "https://randomuser.me/api/portraits/women/38.jpg",
  },
  {
    name: "Toivo Murto",
    email: "toivo.murto@example.com",
    password: "Abcd@1234",
    date_of_birth: "1946-09-26",
    phone_number: "04-803-203",
    address: "5822 Siilitie Paimio Finland",
    image_url: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    name: "June Oterhals",
    email: "june.oterhals@example.com",
    password: "Abcd@1234",
    date_of_birth: "1967-07-10",
    phone_number: "74567994",
    address: "5210 Darres gate Vadfoss Norway",
    image_url: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    name: "Aarush Banerjee",
    email: "aarush.banerjee@example.com",
    password: "Abcd@1234",
    date_of_birth: "1986-06-02",
    phone_number: "7082963083",
    address: "7033 Kazimar St Nashik India",
    image_url: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    name: "Angelina Noel",
    email: "angelina.noel@example.com",
    password: "Abcd@1234",
    date_of_birth: "1998-12-24",
    phone_number: "077 942 67 20",
    address: "2869 Place du 22 Novembre 1943 Kerzers Switzerland",
    image_url: "https://randomuser.me/api/portraits/women/51.jpg",
  },
  {
    name: "Diotil da Rosa",
    email: "diotil.darosa@example.com",
    password: "Abcd@1234",
    date_of_birth: "1969-01-11",
    phone_number: "(80) 9666-9067",
    address: "4409 Rua Paraíba  Ponta Grossa Brazil",
    image_url: "https://randomuser.me/api/portraits/men/81.jpg",
  },
  {
    name: "Evelyn Green",
    email: "evelyn.green@example.com",
    password: "Abcd@1234",
    date_of_birth: "1954-09-12",
    phone_number: "(907) 405-8677",
    address: "1517 Ranchview Dr Shelby United States",
    image_url: "https://randomuser.me/api/portraits/women/31.jpg",
  },
  {
    name: "Oliver Christensen",
    email: "oliver.christensen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1971-05-24",
    phone_number: "58447971",
    address: "3576 Bogfinkevej København S Denmark",
    image_url: "https://randomuser.me/api/portraits/men/89.jpg",
  },
  {
    name: "Debbie Hughes",
    email: "debbie.hughes@example.com",
    password: "Abcd@1234",
    date_of_birth: "1969-08-17",
    phone_number: "09-6200-9470",
    address: "3819 Brown Terrace Tamworth Australia",
    image_url: "https://randomuser.me/api/portraits/women/49.jpg",
  },
  {
    name: "Magnus Olsen",
    email: "magnus.olsen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1985-05-11",
    phone_number: "95112336",
    address: "290 Nylandsvej Aarhus Denmark",
    image_url: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    name: "Abdulrahman Gjedrem",
    email: "abdulrahman.gjedrem@example.com",
    password: "Abcd@1234",
    date_of_birth: "1999-06-07",
    phone_number: "75808776",
    address: "1738 Løkkaskogen Løiten Brænderi Norway",
    image_url: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    name: "Wopke Den Os",
    email: "wopke.denos@example.com",
    password: "Abcd@1234",
    date_of_birth: "1949-10-17",
    phone_number: "(059) 1611775",
    address: "54 Engelberterweg Leens Netherlands",
    image_url: "https://randomuser.me/api/portraits/men/29.jpg",
  },
  {
    name: "Ernesto Molina",
    email: "ernesto.molina@example.com",
    password: "Abcd@1234",
    date_of_birth: "1948-04-25",
    phone_number: "(698) 117 4550",
    address: "1268 Peatonal Norte Salas G.Rodrigo M. Quevedo (Pto.P.) Mexico",
    image_url: "https://randomuser.me/api/portraits/men/92.jpg",
  },
  {
    name: "Lidija Šarić",
    email: "lidija.saric@example.com",
    password: "Abcd@1234",
    date_of_birth: "1984-08-26",
    phone_number: "024-8053-937",
    address: "5745 Kuzminska Ljubovija Serbia",
    image_url: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    name: "Mathieu Mercier",
    email: "mathieu.mercier@example.com",
    password: "Abcd@1234",
    date_of_birth: "1946-10-15",
    phone_number: "02-87-30-01-25",
    address: "1763 Rue Gasparin Avignon France",
    image_url: "https://randomuser.me/api/portraits/men/88.jpg",
  },
  {
    name: "Kimberly Peters",
    email: "kimberly.peters@example.com",
    password: "Abcd@1234",
    date_of_birth: "1982-07-01",
    phone_number: "041-882-6015",
    address: "1876 O'Connell Street Portlaoise Ireland",
    image_url: "https://randomuser.me/api/portraits/women/75.jpg",
  },
  {
    name: "Pablo Moreno",
    email: "pablo.moreno@example.com",
    password: "Abcd@1234",
    date_of_birth: "1994-03-12",
    phone_number: "942-908-631",
    address: "9736 Calle de Téllez Gijón Spain",
    image_url: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    name: "Akash Saha",
    email: "akash.saha@example.com",
    password: "Abcd@1234",
    date_of_birth: "1970-07-07",
    phone_number: "9782016158",
    address: "4916 NAD X Rd New Delhi India",
    image_url: "https://randomuser.me/api/portraits/men/83.jpg",
  },
  {
    name: "Ruben Brooks",
    email: "ruben.brooks@example.com",
    password: "Abcd@1234",
    date_of_birth: "1948-04-19",
    phone_number: "051-277-2420",
    address: "5629 Park Avenue Castlebar Ireland",
    image_url: "https://randomuser.me/api/portraits/men/43.jpg",
  },
  {
    name: "Falko Mittmann",
    email: "falko.mittmann@example.com",
    password: "Abcd@1234",
    date_of_birth: "1990-08-05",
    phone_number: "0496-4030616",
    address: "1832 Marktplatz Hann. Münden Germany",
    image_url: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    name: "Anne-Marie Stefan",
    email: "anne-marie.stefan@example.com",
    password: "Abcd@1234",
    date_of_birth: "1965-02-23",
    phone_number: "0841-3932413",
    address: "1703 Am Bahnhof Pressath Germany",
    image_url: "https://randomuser.me/api/portraits/women/59.jpg",
  },
  {
    name: "Phoebe Davidson",
    email: "phoebe.davidson@example.com",
    password: "Abcd@1234",
    date_of_birth: "1986-08-29",
    phone_number: "01202 549864",
    address: "9980 Queen Street Liverpool United Kingdom",
    image_url: "https://randomuser.me/api/portraits/women/51.jpg",
  },
  {
    name: "Dylan Lowe",
    email: "dylan.lowe@example.com",
    password: "Abcd@1234",
    date_of_birth: "1977-02-26",
    phone_number: "071-057-8296",
    address: "706 Patrick Street Greystones Ireland",
    image_url: "https://randomuser.me/api/portraits/men/23.jpg",
  },
  {
    name: "Donita Shayana",
    email: "donita.shayana@example.com",
    password: "Abcd@1234",
    date_of_birth: "1972-10-21",
    phone_number: "9342704430",
    address: "6740 Janpath Ratlam India",
    image_url: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    name: "Luitgard Kämmerer",
    email: "luitgard.kammerer@example.com",
    password: "Abcd@1234",
    date_of_birth: "1959-08-30",
    phone_number: "0878-8812991",
    address: "1105 Am Sportplatz Altena Germany",
    image_url: "https://randomuser.me/api/portraits/women/93.jpg",
  },
  {
    name: "آرسین احمدی",
    email: "arsyn.hmdy@example.com",
    password: "Abcd@1234",
    date_of_birth: "1988-04-07",
    phone_number: "047-97572864",
    address: "1832 پاتریس لومومبا شهریار Iran",
    image_url: "https://randomuser.me/api/portraits/men/62.jpg",
  },
  {
    name: "Vedat Menemencioğlu",
    email: "vedat.menemencioglu@example.com",
    password: "Abcd@1234",
    date_of_birth: "1989-09-27",
    phone_number: "(164)-302-0346",
    address: "7647 Necatibey Cd İstanbul Turkey",
    image_url: "https://randomuser.me/api/portraits/men/84.jpg",
  },
  {
    name: "Lionel David",
    email: "lionel.david@example.com",
    password: "Abcd@1234",
    date_of_birth: "1955-08-19",
    phone_number: "075 258 55 62",
    address: "4694 Rue Courbet Rhäzüns Switzerland",
    image_url: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    name: "Adolf Schreyer",
    email: "adolf.schreyer@example.com",
    password: "Abcd@1234",
    date_of_birth: "1987-03-21",
    phone_number: "0172-0170104",
    address: "5489 Lindenweg Nortorf Germany",
    image_url: "https://randomuser.me/api/portraits/men/77.jpg",
  },
  {
    name: "Celia Laboy",
    email: "celia.laboy@example.com",
    password: "Abcd@1234",
    date_of_birth: "1991-10-10",
    phone_number: "(653) 707 7137",
    address: "1111 Corredor Mayorga Ruben Jaramillo Mexico",
    image_url: "https://randomuser.me/api/portraits/women/73.jpg",
  },
  {
    name: "Storm Thomsen",
    email: "storm.thomsen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1989-05-10",
    phone_number: "70979043",
    address: "5665 Færøvej Lintrup Denmark",
    image_url: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    name: "Samu Jokinen",
    email: "samu.jokinen@example.com",
    password: "Abcd@1234",
    date_of_birth: "1952-04-06",
    phone_number: "05-096-380",
    address: "8676 Pirkankatu Virrat Finland",
    image_url: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Ellen George",
    email: "ellen.george@example.com",
    password: "Abcd@1234",
    date_of_birth: "1947-09-27",
    phone_number: "051-680-8370",
    address: "4399 High Street Limerick Ireland",
    image_url: "https://randomuser.me/api/portraits/women/24.jpg",
  },
  {
    name: "Salvador Villa",
    email: "salvador.villa@example.com",
    password: "Abcd@1234",
    date_of_birth: "1957-11-05",
    phone_number: "(654) 103 0070",
    address: "829 Diagonal Chile Mexquitic de Carmona Mexico",
    image_url: "https://randomuser.me/api/portraits/men/69.jpg",
  },
  {
    name: "Pavitra Nand",
    email: "pavitra.nand@example.com",
    password: "Abcd@1234",
    date_of_birth: "1966-09-09",
    phone_number: "7883733487",
    address: "8606 Santhekatte Gorakhpur India",
    image_url: "https://randomuser.me/api/portraits/women/83.jpg",
  },
  {
    name: "José Domínguez",
    email: "jose.dominguez@example.com",
    password: "Abcd@1234",
    date_of_birth: "1996-03-29",
    phone_number: "929-872-736",
    address: "1820 Avenida de Andalucía Torrente Spain",
    image_url: "https://randomuser.me/api/portraits/men/95.jpg",
  },
  {
    name: "Kenan Akyüz",
    email: "kenan.akyuz@example.com",
    password: "Abcd@1234",
    date_of_birth: "1959-05-10",
    phone_number: "(517)-826-6762",
    address: "7934 Necatibey Cd Osmaniye Turkey",
    image_url: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    name: "محمدطاها نجاتی",
    email: "mhmdth.njty@example.com",
    password: "Abcd@1234",
    date_of_birth: "1967-08-27",
    phone_number: "091-60583736",
    address: "9056 مقدس اردبیلی بابل Iran",
    image_url: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    name: "Melissa Nägele",
    email: "melissa.nagele@example.com",
    password: "Abcd@1234",
    date_of_birth: "1947-12-05",
    phone_number: "0130-3622482",
    address: "2608 Rosenstraße Schmalkalden-Meiningen Germany",
    image_url: "https://randomuser.me/api/portraits/women/49.jpg",
  },
  {
    name: "سپهر یاسمی",
    email: "sphr.ysmy@example.com",
    password: "Abcd@1234",
    date_of_birth: "1975-02-26",
    phone_number: "090-55327006",
    address: "2917 واعظی آمل Iran",
    image_url: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    name: "Vincent Kowalski",
    email: "vincent.kowalski@example.com",
    password: "Abcd@1234",
    date_of_birth: "1981-08-28",
    phone_number: "N98 H41-6209",
    address: "5728 Dieppe Ave Hampstead Canada",
    image_url: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    name: "Irena Gautier",
    email: "irena.gautier@example.com",
    password: "Abcd@1234",
    date_of_birth: "1948-08-27",
    phone_number: "076 718 45 48",
    address: "3294 Rue du Bon-Pasteur Olsberg Switzerland",
    image_url: "https://randomuser.me/api/portraits/women/94.jpg",
  },
];

let done;
const generateDummyUser = async () => {
  if (done) return;
  for (let index = 0; index < users.length; index++) {
    const user = users[index];
    const hashedPassword = await bcrypt.hash(user.password, 12);
    user.password = hashedPassword;
    await userModel.create(user);
  }
  done = true;
  console.log("done: ", users.length);
};

export default generateDummyUser;
